config/routes.rb
Rails.application.routes.draw do
  
  resources :featured_trailors
  resources :banners
  post '/rate' => 'rater#create', :as => 'rate'
  mount Ckeditor::Engine => '/ckeditor'
  root 'home#index'
  get '/' => "home#index", as: :user_root
  
  get 'home/index'
  get 'home/about'
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup
  match '/reviews/new/:id' => 'reviews#new', :as => :movie_with_review, via: :get
  match '/movie/:id' => 'home#movie_detail', :as => :movie_with_title, via: :get
  match '/movies/types/:id' => 'home#movie_types', :as => :type_with_title, via: :get
  match '/movies/genres/:id' => 'home#movie_genres', :as => :genre_with_title, via: :get  
  match 'movies/top_rated_movies/bollywood' => 'home#bollywood_top_rated', via: :get
  match 'movies/upcoming_movies/bollywood' => 'home#bollywood_upcoming', via: :get
  match '/movies/latest_movies/bollywood' => 'home#bollywood_latest', via: :get

  match 'movies/top_rated_movies/hollywood' => 'home#hollywood_top_rated', via: :get
  match 'movies/upcoming_movies/hollywood' => 'home#hollywood_upcoming', via: :get
  match '/movies/latest_movies/hollywood' => 'home#hollywood_latest', via: :get

  match 'movies/bollywood_movies' => 'home#bollywood_movies', via: :get
  match 'movies/hollywood_movies' => 'home#hollywood_movies', via: :get
  match '/contact' => 'contacts#new', :as => :contact, via: :get
  resources :contacts
  resources :reviews
  resources :movies
  resources :movies do
    collection do
      get 'bollywood_hungama'
      post 'bollywood_hungama'
      patch 'bollywood_hungama'
    end
    collection do
      get 'hungama_url'
      post 'hungama_url'
      patch 'hungama_url'
    end
    collection do
      get 'mov_with_critic'
      post 'mov_with_critic'
      patch 'mov_with_critic'
    end
  end
  devise_for :admins, controllers: { sessions: "admins/sessions" }
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks', passwords: 'users/passwords', confirmations: 'users/confirmations' }
  
  namespace :api do
    namespace :v1 do
      resources :movies, only: [:index,:show] do
        collection do
          post 'getTopRatedMovies'      
          post 'getLatestMovies'
          post 'getUpcomingMovies'
          post 'getMovies' 
          get 'terms'
          post 'moviedetails' 
          post 'userSaveRating'
        end
      end
      resources :users, only: [:show, :create] do
        collection do
          post 'login'
          post 'register'
          post 'forgetpass'
          post 'saveRegID'
        end
      end
    end
  end

end

app/models/featured_trailor.rb
class FeaturedTrailor < ActiveRecord::Base
	belongs_to :movie
	validates :movie, presence: true
	validates :position, numericality: { greater_than_or_equal_to: 1, less_than_or_equal_to: 3}
	
end

app/controllers/featured_trailors_controller.rb
class FeaturedTrailorsController < ApplicationController
  before_action :set_featured_trailor, only: [:show, :edit, :update, :destroy]

  # GET /featured_trailors
  # GET /featured_trailors.json
  def index
    @featured_trailors = FeaturedTrailor.all
  end

  # GET /featured_trailors/1
  # GET /featured_trailors/1.json
  def show
  end

  # GET /featured_trailors/new
  def new
    @featured_trailor = FeaturedTrailor.new
  end

  # GET /featured_trailors/1/edit
  def edit
  end

  # POST /featured_trailors
  # POST /featured_trailors.json
  def create
    @featured_trailor = FeaturedTrailor.new(featured_trailor_params)

    respond_to do |format|
      if @featured_trailor.save
        format.html { redirect_to @featured_trailor, notice: 'Featured trailor was successfully created.' }
        format.json { render :show, status: :created, location: @featured_trailor }
      else
        format.html { render :new }
        format.json { render json: @featured_trailor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /featured_trailors/1
  # PATCH/PUT /featured_trailors/1.json
  def update
    respond_to do |format|
      if @featured_trailor.update(featured_trailor_params)
        format.html { redirect_to @featured_trailor, notice: 'Featured trailor was successfully updated.' }
        format.json { render :show, status: :ok, location: @featured_trailor }
      else
        format.html { render :edit }
        format.json { render json: @featured_trailor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /featured_trailors/1
  # DELETE /featured_trailors/1.json
  def destroy
    @featured_trailor.destroy
    respond_to do |format|
      format.html { redirect_to featured_trailors_url, notice: 'Featured trailor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_featured_trailor
      @featured_trailor = FeaturedTrailor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def featured_trailor_params
      params.require(:featured_trailor).permit(:movie_id, :position)
    end
end

app/helpers/featured_trailors_helper.rb
module FeaturedTrailorsHelper
end

app/views/featured_trailors/_form.html.erb
<%= form_for(@featured_trailor) do |f| %>
  <% if @featured_trailor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@featured_trailor.errors.count, "error") %> prohibited this featured_trailor from being saved:</h2>

      <ul>
      <% @featured_trailor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :movie_id %><br>
    <%= f.number_field :movie_id %>
  </div>
  <div class="field">
    <%= f.label :position %><br>
    <%= f.number_field :position %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/featured_trailors/edit.html.erb
<h1>Editing Featured Trailor</h1>

<%= render 'form' %>

<%= link_to 'Show', @featured_trailor %> |
<%= link_to 'Back', featured_trailors_path %>

app/views/featured_trailors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Featured Trailors</h1>

<table>
  <thead>
    <tr>
      <th>Movie</th>
      <th>Position</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @featured_trailors.each do |featured_trailor| %>
      <tr>
        <td><%= featured_trailor.movie_id %></td>
        <td><%= featured_trailor.position %></td>
        <td><%= link_to 'Show', featured_trailor %></td>
        <td><%= link_to 'Edit', edit_featured_trailor_path(featured_trailor) %></td>
        <td><%= link_to 'Destroy', featured_trailor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Featured trailor', new_featured_trailor_path %>

app/views/featured_trailors/new.html.erb
<h1>New Featured Trailor</h1>

<%= render 'form' %>

<%= link_to 'Back', featured_trailors_path %>

app/views/featured_trailors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Movie:</strong>
  <%= @featured_trailor.movie_id %>
</p>

<p>
  <strong>Position:</strong>
  <%= @featured_trailor.position %>
</p>

<%= link_to 'Edit', edit_featured_trailor_path(@featured_trailor) %> |
<%= link_to 'Back', featured_trailors_path %>