config/routes.rb
Rails.application.routes.draw do
  
  resources :featured_trailors
  resources :banners
  post '/rate' => 'rater#create', :as => 'rate'
  mount Ckeditor::Engine => '/ckeditor'
  root 'home#index'
  get '/' => "home#index", as: :user_root
  
  get 'home/index'
  get 'home/about'
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup
  match '/reviews/new/:id' => 'reviews#new', :as => :movie_with_review, via: :get
  match '/movie/:id' => 'home#movie_detail', :as => :movie_with_title, via: :get
  match '/movies/types/:id' => 'home#movie_types', :as => :type_with_title, via: :get
  match '/movies/genres/:id' => 'home#movie_genres', :as => :genre_with_title, via: :get  
  match 'movies/top_rated_movies/bollywood' => 'home#bollywood_top_rated', via: :get
  match 'movies/upcoming_movies/bollywood' => 'home#bollywood_upcoming', via: :get
  match '/movies/latest_movies/bollywood' => 'home#bollywood_latest', via: :get

  match 'movies/top_rated_movies/hollywood' => 'home#hollywood_top_rated', via: :get
  match 'movies/upcoming_movies/hollywood' => 'home#hollywood_upcoming', via: :get
  match '/movies/latest_movies/hollywood' => 'home#hollywood_latest', via: :get

  match 'movies/bollywood_movies' => 'home#bollywood_movies', via: :get
  match 'movies/hollywood_movies' => 'home#hollywood_movies', via: :get
  match '/contact' => 'contacts#new', :as => :contact, via: :get
  resources :contacts
  resources :reviews
  resources :movies
  resources :movies do
    collection do
      get 'bollywood_hungama'
      post 'bollywood_hungama'
      patch 'bollywood_hungama'
    end
    collection do
      get 'hungama_url'
      post 'hungama_url'
      patch 'hungama_url'
    end
    collection do
      get 'mov_with_critic'
      post 'mov_with_critic'
      patch 'mov_with_critic'
    end
  end
  devise_for :admins, controllers: { sessions: "admins/sessions" }
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks', passwords: 'users/passwords', confirmations: 'users/confirmations' }
  
  namespace :api do
    namespace :v1 do
      resources :movies, only: [:index,:show] do
        collection do
          post 'getTopRatedMovies'      
          post 'getLatestMovies'
          post 'getUpcomingMovies'
          post 'getMovies' 
          get 'terms'
          post 'moviedetails' 
          post 'userSaveRating'
        end
      end
      resources :users, only: [:show, :create] do
        collection do
          post 'login'
          post 'register'
          post 'forgetpass'
          post 'saveRegID'
        end
      end
    end
  end

end

app/models/banner.rb
class Banner < ActiveRecord::Base
	mount_uploader :banner, BannerUploader
	validates :ad_type, presence: true
	validates :position, presence: true
	validates :order, numericality: { greater_than_or_equal_to: 1 }

	def position_enum
		['Header', 'Sidebar', 'Movie Detail Top', 'Movie Detail Bottom', 
			'Index Top', 'Index In between', 'Index Bottom', 'Genre Top', 'Genre Bottom', 
			'Top Rated Top', 'Top Rated In between', 'Top Rated Bottom', 'Upcoming Bottom', 'Upcoming In between', 'Upcoming Top', 
			'Page Top', 'Page Bottom', 'Latest Top', 'Latest In between', 'Latest Bottom']
	end

	def size_enum
		['300*600', '300*250', '336*280', '320*50', '728*90', '160*600']
	end

	def ad_type_enum
		['Text', 'Banner', 'Google Ad']		
	end
end

app/controllers/banners_controller.rb
class BannersController < ApplicationController
  before_action :set_banner, only: [:show, :edit, :update, :destroy]

  # GET /banners
  # GET /banners.json
  def index
    @banners = Banner.all
  end

  # GET /banners/1
  # GET /banners/1.json
  def show
  end

  # GET /banners/new
  def new
    @banner = Banner.new
  end

  # GET /banners/1/edit
  def edit
  end

  # POST /banners
  # POST /banners.json
  def create
    @banner = Banner.new(banner_params)

    respond_to do |format|
      if @banner.save
        format.html { redirect_to @banner, notice: 'Banner was successfully created.' }
        format.json { render :show, status: :created, location: @banner }
      else
        format.html { render :new }
        format.json { render json: @banner.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /banners/1
  # PATCH/PUT /banners/1.json
  def update
    respond_to do |format|
      if @banner.update(banner_params)
        format.html { redirect_to @banner, notice: 'Banner was successfully updated.' }
        format.json { render :show, status: :ok, location: @banner }
      else
        format.html { render :edit }
        format.json { render json: @banner.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /banners/1
  # DELETE /banners/1.json
  def destroy
    @banner.destroy
    respond_to do |format|
      format.html { redirect_to banners_url, notice: 'Banner was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_banner
      @banner = Banner.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def banner_params
      params.require(:banner).permit(:image, :link, :text, :position)
    end
end

app/helpers/banners_helper.rb
module BannersHelper
end

app/views/banners/_form.html.erb
<%= form_for(@banner) do |f| %>
  <% if @banner.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@banner.errors.count, "error") %> prohibited this banner from being saved:</h2>

      <ul>
      <% @banner.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :image %><br>
    <%= f.text_field :image %>
  </div>
  <div class="field">
    <%= f.label :link %><br>
    <%= f.text_field :link %>
  </div>
  <div class="field">
    <%= f.label :text %><br>
    <%= f.text_field :text %>
  </div>
  <div class="field">
    <%= f.label :position %><br>
    <%= f.text_field :position %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/banners/edit.html.erb
<h1>Editing Banner</h1>

<%= render 'form' %>

<%= link_to 'Show', @banner %> |
<%= link_to 'Back', banners_path %>

app/views/banners/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Banners</h1>

<table>
  <thead>
    <tr>
      <th>Image</th>
      <th>Link</th>
      <th>Text</th>
      <th>Position</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @banners.each do |banner| %>
      <tr>
        <td><%= banner.image %></td>
        <td><%= banner.link %></td>
        <td><%= banner.text %></td>
        <td><%= banner.position %></td>
        <td><%= link_to 'Show', banner %></td>
        <td><%= link_to 'Edit', edit_banner_path(banner) %></td>
        <td><%= link_to 'Destroy', banner, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Banner', new_banner_path %>

app/views/banners/new.html.erb
<h1>New Banner</h1>

<%= render 'form' %>

<%= link_to 'Back', banners_path %>

app/views/banners/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Image:</strong>
  <%= @banner.image %>
</p>

<p>
  <strong>Link:</strong>
  <%= @banner.link %>
</p>

<p>
  <strong>Text:</strong>
  <%= @banner.text %>
</p>

<p>
  <strong>Position:</strong>
  <%= @banner.position %>
</p>

<%= link_to 'Edit', edit_banner_path(@banner) %> |
<%= link_to 'Back', banners_path %>