config/routes.rb
Rails.application.routes.draw do
  
  resources :featured_trailors
  resources :banners
  post '/rate' => 'rater#create', :as => 'rate'
  mount Ckeditor::Engine => '/ckeditor'
  root 'home#index'
  get '/' => "home#index", as: :user_root
  
  get 'home/index'
  get 'home/about'
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup
  match '/reviews/new/:id' => 'reviews#new', :as => :movie_with_review, via: :get
  match '/movie/:id' => 'home#movie_detail', :as => :movie_with_title, via: :get
  match '/movies/types/:id' => 'home#movie_types', :as => :type_with_title, via: :get
  match '/movies/genres/:id' => 'home#movie_genres', :as => :genre_with_title, via: :get  
  match 'movies/top_rated_movies/bollywood' => 'home#bollywood_top_rated', via: :get
  match 'movies/upcoming_movies/bollywood' => 'home#bollywood_upcoming', via: :get
  match '/movies/latest_movies/bollywood' => 'home#bollywood_latest', via: :get

  match 'movies/top_rated_movies/hollywood' => 'home#hollywood_top_rated', via: :get
  match 'movies/upcoming_movies/hollywood' => 'home#hollywood_upcoming', via: :get
  match '/movies/latest_movies/hollywood' => 'home#hollywood_latest', via: :get

  match 'movies/bollywood_movies' => 'home#bollywood_movies', via: :get
  match 'movies/hollywood_movies' => 'home#hollywood_movies', via: :get
  match '/contact' => 'contacts#new', :as => :contact, via: :get
  resources :contacts
  resources :reviews
  resources :movies
  resources :movies do
    collection do
      get 'bollywood_hungama'
      post 'bollywood_hungama'
      patch 'bollywood_hungama'
    end
    collection do
      get 'hungama_url'
      post 'hungama_url'
      patch 'hungama_url'
    end
    collection do
      get 'mov_with_critic'
      post 'mov_with_critic'
      patch 'mov_with_critic'
    end
  end
  devise_for :admins, controllers: { sessions: "admins/sessions" }
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks', passwords: 'users/passwords', confirmations: 'users/confirmations' }
  
  namespace :api do
    namespace :v1 do
      resources :movies, only: [:index,:show] do
        collection do
          post 'getTopRatedMovies'      
          post 'getLatestMovies'
          post 'getUpcomingMovies'
          post 'getMovies' 
          get 'terms'
          post 'moviedetails' 
          post 'userSaveRating'
        end
      end
      resources :users, only: [:show, :create] do
        collection do
          post 'login'
          post 'register'
          post 'forgetpass'
          post 'saveRegID'
        end
      end
    end
  end

end

app/views/layouts/_footer.html.erb
<!--Footer-->
<footer id="footer">
	<div class="container">
		<div class="row-fluid">
			<div class="span5 cp">
				&copy; 2016 <a target="_blank" href="http://shapebootstrap.net/" title="Free Twitter Bootstrap WordPress Themes and HTML templates">Vivacity Team</a>. All Rights Reserved.
			</div>
			<!--/Copyright-->

			<div class="span6">
				<ul class="social pull-right">
					<div class="fb-like" data-href="https://www.facebook.com/moviereport.in/" data-width="150" data-layout="standard" data-action="like" data-show-faces="false" data-share="true"></div>                  
				</ul>
			</div>

			<!-- <div class="span1">
				<a id="gototop" class="gototop pull-right" href="#"><i class="icon-angle-up"></i></a>
			</div> -->
			<!--/Goto Top-->
		</div>
	</div>
</footer>
<!--/Footer-->

app/views/layouts/_genres.html.erb
<div class="widget">
	<h3>Browse by Genres</h3>
	<div>
		<div class="row-fluid">
			<% @total_genre = @genres.count/2.0 %>
			<% @span1 = @total_genre.ceil %>
			<% @span2 = @total_genre.floor %>
			<% @span1_genre = @genres.first(@span1) %>
			<% @span2_genre = @genres.last(@span2) %>

				<div class="span6">
						<ul class="unstyled">
							<% @span1_genre.each do |genre| %>
								<% if genre.movies.count > 0 %>
									<li><%= link_to genre.title, genre_with_title_path(genre) %> (<%= genre.movies.count %>)</li>
								<% end %>
							<% end %>
						</ul>
				</div>

				<div class="span6">
						<ul class="unstyled">
							<% @span2_genre.each do |genre| %>
								<% if genre.movies.count > 0 %>
									<li><%= link_to genre.title, genre_with_title_path(genre) %> (<%= genre.movies.count %>)</li>
								<% end %>                 
							<% end %>
						</ul>
				</div>			
		</div>
	</div>                       
</div>

app/views/layouts/_header.html.erb
<!--Header-->
	<header class="navbar navbar-fixed-top">
		<div class="navbar-inner">
			<div class="container">
				<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</a>
				<%= link_to image_tag("/assets/logo.png"), root_path, {:class => "pull-left", :id => "logo", :class => "logo_back" } %>
				<div class="nav-collapse collapse pull-right">
					<ul class="nav">
						<li><%= nav_link "Home", root_path %></li>
						<!-- <li><%#= nav_link "Top Rated", movies_top_rated_movies_path %></li>
						<li><%#= nav_link "Latest", movies_latest_movies_path %></li>
						<li><%#= nav_link "Upcoming", movies_upcoming_movies_path %></li> -->

						<li class="dropdown">
							<%= link_to 'Top Rated <i class="icon-angle-down"></i>'.html_safe, '#', { :class => 'dropdown-toggle', 'data-toggle' => 'dropdown' } %>
							<ul class="dropdown-menu">
								<li><%= nav_link "Bollywood", movies_top_rated_movies_bollywood_path %></li>
								<li><%= nav_link "Hollywood", movies_top_rated_movies_hollywood_path %></li>
							</ul>
						</li>

						<li class="dropdown">
							<%= link_to 'Latest <i class="icon-angle-down"></i>'.html_safe, '#', { :class => 'dropdown-toggle', 'data-toggle' => 'dropdown' } %>
							<ul class="dropdown-menu">
								<li><%= nav_link "Bollywood",  movies_latest_movies_bollywood_path  %></li>
								<li><%= nav_link "Hollywood", movies_latest_movies_hollywood_path %></li>
							</ul>
						</li>

						<li class="dropdown">

							<%= link_to 'Upcoming <i class="icon-angle-down"></i>'.html_safe, '#', { :class => 'dropdown-toggle', 'data-toggle' => 'dropdown' } %>
								<ul class="dropdown-menu">
									<li><%= nav_link "Bollywood", movies_upcoming_movies_bollywood_path %></li>
									<li><%= nav_link "Hollywood", movies_upcoming_movies_hollywood_path %></li>
								</ul>
						</li>

						<li><%= nav_link "Contact Us", contact_path %></li>
						<li><%= nav_link "About Us", home_about_path %></li>
						<li class="login dropdown">
							<% if user_signed_in? %>
								<%= link_to "Sign out", destroy_user_session_path %>
							<% else %>
								<%= link_to new_user_session_path do %>
	    						<i class="icon-lock"></i>
								<% end %>
							<% end %>
						</li>
					</ul>        
				</div><!--/.nav-collapse -->
			</div>
		</div>
	</header>

	<style type="text/css">
	.logo_back img{
		height: 90px;
	}

	.dropdown-menu > .active > a, .dropdown-menu > .active > a:hover, .dropdown-menu > .active > a:focus, .dropdown-menu > li > a:hover, .dropdown-menu > li > a:focus, .dropdown-submenu:hover > a, .dropdown-submenu:focus > a {
    background: #0997f0 none repeat scroll 0 0;
}

header .dropdown-menu {
    margin-top: 0px! important;
}
	</style>
	
	<%#= @banners.where(:ad_type => 'Text').first.text %>
	<!-- /header -->

app/views/layouts/_movietype.html.erb
<div class="widget">
	<h3>Browse by Types</h3>
	<div>
		<div class="row-fluid">
			<% @total_types = @movie_types.count/2.0 %>
			<% @span1 = @total_types.ceil %>
			<% @span2 = @total_types.floor %>
			<% @span1_type = @movie_types.first(@span1) %>
			<% @span2_type = @movie_types.last(@span2) %>

				<div class="span6">
						<ul class="unstyled">
							<% @span1_type.each do |type| %>
								<li><%= link_to type.title, type_with_title_path(type) %></li>                     
							<% end %>
						</ul>
				</div>

				<div class="span6">
						<ul class="unstyled">
							<% @span2_type.each do |type| %>
								<li><%= link_to type.title, type_with_title_path(type) %></li>                     
							<% end %>
						</ul>
				</div>			
		</div>
	</div>                       
</div>

app/views/layouts/_sidebar_banner.html.erb
<div class="widget widget-popular">
	<div class="widget-blog-items">
		<% @sidebar_banners.each do |banner| %>
			<% if banner.ad_type == 'Text' %>
				<div class="widget-blog-item media">					
					<div class="media-body">			
						<!-- <div class=""> -->
							<div class="<%= banner.ad_type%>-<%= banner.id %>" style="width: 100%; background-color: pink; "><%= banner.text.html_safe %>
							</div>
						<!-- </div> -->
					</div>
				</div>
			<% end %>

			<% if banner.ad_type == 'Banner' %>
				<div class="widget-blog-item media">					
					<div class="media-body">			
						<!-- <div class=""> -->
							<div class="<%= banner.ad_type%>-<%= banner.id %>" style="width: 100%; text-align:left;">
								<% if banner.link.present? %>
									<%= link_to( image_tag(banner.banner), banner.link) %>
								<% else %>
									<%= image_tag(banner.banner) %>
								<% end %>
							</div>
						<!-- </div> -->
					</div>
				</div>
			<% end %>

			<% if banner.ad_type == 'Google Ad' %>
				<div class="widget-blog-item media">					
					<div class="media-body">
						<div class="<%= banner.ad_type%>-<%= banner.id %>" style="width: 100%;">
							<%= raw banner.google_add_js %>
						</div>
					</div>
				</div>
			<% end %>
		<% end %>
	</div>  
	<br/>
	<div class="fb-page" data-href="https://www.facebook.com/moviereport.in/" data-tabs="timeline" data-width="400" data-height="400" data-small-header="false" data-adapt-container-width="true" data-hide-cover="false" data-show-facepile="true"><div class="fb-xfbml-parse-ignore"><blockquote cite="https://www.facebook.com/moviereport.in/"><a href="https://www.facebook.com/moviereport.in/">Movie Review</a></blockquote></div></div>                      
</div>

app/views/layouts/_top_rated.html.erb
<div class="widget widget-popular top_right">
	<h3>Top Rated Movies</h3>
	<div class="widget-blog-items">
		<% @top_movies.first(5).each do |movie| %>
			<div class="widget-blog-item media">
				<div class="pull-left">
					<div class="date">
						<span class="month"><%= movie.release_date.strftime("%b") %></span>
						<span class="day"><%= movie.release_date.strftime("%d") %></span>
					</div>
				</div>
				<div class="media-body"><h5>
					<%= link_to movie.title, movie_with_title_path(movie) %></h5>
					<p class="movie_rating-<%= movie.id %>"></p>
					<script type="text/javascript">
						$(function(){
							$.getScript( "https://cdnjs.cloudflare.com/ajax/libs/raty/2.7.0/jquery.raty.min.js", function( data, textStatus, jqxhr ) {
									$('.movie_rating-<%= movie.id %>').raty({ score: <%= movie.rating %>,
							  	readOnly: true,
						    	path: '/assets'
								});
							})
						})
					</script>
					<!-- <a href="#"><h5>Duis sed odio sit amet nibh vulputate cursus a sit amet mauris</h5></a> -->
				</div>
			</div>
		<% end %>
		<% if @top_movies.count > 5 %>
			<h5>
				<%= link_to 'View More' ,  movies_top_rated_movies_bollywood_path , :class => "viewmore" %>
			</h5>
		<% end %>
	</div>                        
</div>
<br/>
<br/>

<div class="widget widget-popular">
	<h3>Upcoming Movies</h3>
	<div class="widget-blog-items">
		<% @upcoming.first(2).each do |movie| %>			
			<div class="widget-blog-item media">
				<div class="pull-left">
					<div class="date">
						<span class="month"><%= movie.release_date.strftime("%b") %></span>
						<span class="day"><%= movie.release_date.strftime("%d") %></span>
					</div>
				</div>
				<div class="media-body">

					<h5>

						<% if movie.image.present? %>
							<%= link_to image_tag(movie.image.thumb.url), movie_with_title_path(movie), :class => 'upcoming_img' %>
						<% else %>
							<%= link_to image_tag("/assets/not_available.jpg"), movie_with_title_path(movie) %>
						<% end %>   
						
						<%= link_to movie.title, movie_with_title_path(movie) %>
					</h5>
				</div>
			</div>			
		<% end %>
		<% if @upcoming.count > 2 %>
			<h5>
				<%= link_to 'View More' ,  movies_upcoming_movies_bollywood_path , :class => "viewmore" %>
			</h5>
		<% end %>
	</div>                        
</div>
<style type="text/css">
	.upcoming_img img {
    height: 220px;
    width: 100%;
}
</style>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<% if controller.controller_name == "home" && controller.action_name == "movie_detail" %>
	
		<title><%= @movie.title %></title>
		<meta name="keywords" content="Movie Reviews, Vivacity Infotech, <%= @movie.star_cast %> <% if @movie.movie_type %>, <%= @movie.movie_type.title %> <% end %> <% if @movie.genres %> , <% @movie.genres.each do |genre| %> <%= genre.title %> <% end %> <% end %>"/>
		<meta name="description" content="<% if @movie.description %><%= description(@movie.description) %> <% end %>" />
	<% else %>
		<title>MovieReview</title>
	<% end %>


	<%= javascript_include_tag 'https://code.jquery.com/jquery-2.2.3.min.js' %>

	
	<%= javascript_include_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js' %>


	<link href="https://fonts.googleapis.com/css?family=Fjalla+One" rel="stylesheet">
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

	<link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-modal/2.2.6/js/bootstrap-modal.min.js">

	<link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
	
	<%= csrf_meta_tags %>
</head>
<body>
<script type="text/javascript">
$(document).ready(function(){
	// alert("hiii");
    $('.navbar .dropdown').hover(function() {
        $(this).find('.dropdown-menu').first().stop(true, true).delay(250).slideDown();
    }, function() {
        $(this).find('.dropdown-menu').first().stop(true, true).delay(100).slideUp()
    });
})
</script>
	

	<% if devise_controller? && resource_name == :admin && action_name == 'new' %>
		<!-- <div class="container"> -->
			<% flash.each do |key, value| %>
				<div class="msgs alert alert-<%= key %>"><%= value %></div>
			<% end %>
		<!-- </div> -->
		<%= yield %>
	<% else %>
		
		<%= render 'layouts/header' %>

		<!-- <div class="container"> -->
			<% flash.each do |key, value| %>
				<div class="msgs alert alert-<%= key %>"><%= value %></div>
			<% end %>
		<!-- </div> -->

			<%= yield %>
			<%= render 'layouts/footer' %>
			<%#= debug(params) if Rails.env.development? %>


		<%#= yield %>
		<%#= render 'layouts/footer' %>
	<% end %>

<!-- Go to www.addthis.com/dashboard to customize your tools -->
	<script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-4f8547fe69c143c2"></script>
	<!-- Go to www.addthis.com/dashboard to customize your tools -->
	<div class="addthis_sharing_toolbox"></div>

	<div id="fb-root"></div>
	<script>(function(d, s, id) {
		var js, fjs = d.getElementsByTagName(s)[0];
		if (d.getElementById(id)) return;
		js = d.createElement(s); js.id = id;
		js.src = "//connect.facebook.net/en_GB/sdk.js#xfbml=1&version=v2.5";
		fjs.parentNode.insertBefore(js, fjs);
	}(document, 'script', 'facebook-jssdk'));</script>

	<div id="fb-root"></div>
	<script>(function(d, s, id) {
		var js, fjs = d.getElementsByTagName(s)[0];
		if (d.getElementById(id)) return;
		js = d.createElement(s); js.id = id;
		js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.5&appId=153808367970167";
		fjs.parentNode.insertBefore(js, fjs);
	}(document, 'script', 'facebook-jssdk'));</script>

</body>

</html>